---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm

trigger:
  branch:
    exclude:
      - main

clone:
  depth: 1

volumes:
  - name: dockersock
    host:
      path: /run/docker.sock

steps:
  - name: Build ${DRONE_REPO} Container Image
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      auto_tag: false
      daemon_off: true
      debug: false
      dockerfile: docker/Dockerfile
      mirror: "https://registry.dragonheim.net/"
      purge: true
      repo: ${DRONE_REPO}
      # target: development
      username:
        from_secret: docker_username
      password:
        from_secret: docker_auth
